version: '3.3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile  
    container_name: php-crud
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80

  db:
    container_name: mysql-crud
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
    - ./docker-storage/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crud
      MYSQL_USER: crud
      MYSQL_PASSWORD: crud
    ports:
      - 3306:3306

# vim: set ts=2 sw=2 sts=2